version: "3.7"

services:
  db:
    image: mariadb:latest
    container_name: nextcloud-db
    volumes:
      - /home/skyscrpr/nextcloud/db/data:/var/lib/mysql
    networks:
      - default
    restart: always
    environment:
      TZ: America/New_York
      MYSQL_ROOT_PASSWORD: hacker405donteventryit!
      MYSQL_DATABASE: db
      MYSQL_USER: skyscrpr
      MYSQL_PASSWORD: hacker405

  redis:
    image: redis:latest
    restart: always
    networks:
      - default
    volumes:
      - /home/skyscrpr/redis:/var/lib/redis

  nextcloud:
    depends_on:
      - redis
      - db
    image: nextcloud:stable
    container_name: nextcloud
    volumes:
      - /home/skyscrpr/nextcloud/data:/var/www/html
    networks:
      - proxy
      - default
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=http"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.skyscrpr.studio`)"
      - "traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-https-redirect"
      - "traefik.http.routers.nextcloud-secure.entrypoints=https"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`nextcloud.skyscrpr.studio`)"
      - "traefik.http.routers.nextcloud-secure.tls=true"
      - "traefik.http.routers.nextcloud-secure.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    environment:
      REDIS_HOST: redis
      MYSQL_HOST: db:3306
      MYSQL_DATABASE: db
      MYSQL_USER: skyscrpr
      MYSQL_PASSWORD: hacker405

networks:
  proxy:
    external: true
